#settings
url_base: "federal-open-source-repos"
title: "Government Open Source Projects"
description: "A dynamically generated list of open source projects hosted on GitHub"
sm_api: "https://raw.githubusercontent.com/gbinal/federal-open-source-repos/gh-pages/list_of_accounts.json"
gh_api: "https://api.github.com/users/<%= account %>/repos?callback=?"
repo: "https://github.com/GSA/federal-open-source-repos"

#build config
server: true
auto: true
exclude: ["node_modules"]

#API Keys to avoid rate limits while deving
client_id: ""
client_secret: ""
